### ISSUE TITLE
uninitialized constant DryCrud::Responder

### ISSUE THREAD

**Issue by jhadeepakkumar14** [codez/dry_crud#10]
class CrudController < ListController

  self.responder = DryCrud::Responder
  ..............
  .............
end

"self.responder = DryCrud::Responder"
This line is generating uninitialized constant DryCrud::Responder error. I am using dry crud in rails engine in my application.

**Comment by codez** [comment]
Did you generate the dry_crud code into your engine or are you using it as a gem? Do your load paths include the relevant directories? Does this work when you use dry_crud directly in the application? Please try to give more details about your setup.

**Comment by jhadeepakkumar14** [comment]
I am using it as a gem, all directory are present, i mean dry_crud folder in controllers, helpers, views are present, I did not written any code to load this file in path, as it is inside app folder so it should be loaded automatically. 

![screenshot from 2016-03-24 15 29 05](https://cloud.githubusercontent.com/assets/3532367/14013911/2f91ccc8-f1d5-11e5-9061-6a02d3a6bbdd.png)

My application structure is, 

App_name
------> admin    This is Rails Engine (Here I am trying to use dry crud gem)
------------> app
------------> bin
------------> config
        .
        .
        .
-----> app
-----> bin
-----> config
   .
   .
   .

Should I need to include the path of dry crud in main application? or it will be automatically loaded in path. Admin Engine is mounted in main application.

**Comment by codez** [comment]
So everything is in the Admin module. Make sure all generated dry_crud classes and modules are also in this Admin module then.

**Comment by jhadeepakkumar14** [comment]
yes, everything is present in admin module.

**Comment by codez** [comment]
Then you should change the failing line to `self.responder = Admin::DryCrud::Responder`. 

I think this is an issue specific to your engine setup and not particularly related to dry_crud.
