### ISSUE TITLE
[PG::UndefinedFunction: ERROR] Search raising errors with date and numeric columns

### ISSUE THREAD

**Issue by mberlanda** [codez/dry_crud#17]
Hi,

I am facing the following error for the controllers where I have in my search columns some `date` or `numeric` fields (such as related models):
```
PG::UndefinedFunction: ERROR:  operator does not exist: date ~~* unknown
LINE 1: ...ents".* FROM "events" WHERE (((((("events"."date" ILIKE '%ap...
```
The error is pretty clear and it's due to the implementation of the search method.

### Feature suggested : Add Datatables for index

I am wondering if you would interested to provide the integration with some table plug-in for jQuery such as [Datatables](https://datatables.net/).

The implementation sounds quite workable to me:

The **Table Builder** should:

- create only the headers of the table
- assign to the table a unique id
- eventually create a div with unique id for table buttons

An haml representation of the output could be:

```haml
.container
  .crud-index-buttons
  %table.table.table-striped.table-bordered#crud-table
    %thead
      - Controller.search_columns.each do |col|
        %tr= I18n.t("something.#{col}", default: col)
```

_May I ask you some help to accomplish this first step?_

The **assets** should include `jquery.js`, `datatables.css`, `datatables.min.js`.

The **routes** should include by default for every controller something like:

```rb
resources :model do
  collection do
    get :datatable_index
  end
end
```
It would be needed a _decorator_ or an _helper_ to transform the `ActiveRecord::Collection` to an array of array of values: e.g. an implementation I did on a previous project using concerns:
```rb
def model_datatable_index(model)
  @response = model.send(:all)
  @data = @response.map { |r| decorator_name.send(:new, r).send(:index) }
  render_datatable_response
end

private

def render_datatable_response
  respond_to do |format|
    format.json { render 'shared/search' }
  end
end
``` 
Where `shared/search` is a jbuilder json:
```rb
# app/views/shared/search.json.jbuilder
json.draw params['draw'].to_i
json.recordsTotal @data.count
json.recordsFiltered @data.count
json.data @data
```
Finally the view should initialize DataTable on document ready.:
```js
$(
  function() {
    initializeCrudTable(url,tableId, buttonsIdOrClass);
  }
)

function initializeCrudTable(url,tableId, buttonsIdOrClass){
  var crudTable = $(tableId).DataTable({
    'buttons': ['copy', 'excel', 'pdf'],
    'processing': true,
    'scrollX': true,
    'pageLength': 50,
    'order': [[1, 'asc']],
    'ordering': true,
    'dom': 'fl<"table-scrollable"t>irp',
    'columnDefs': [
      {
        targets: [],
        orderable: true
      }
    ],
    'ajax': {
      'url': url,
      'method': 'GET'
    }
  });
  new $.fn.dataTable.Buttons( crudTable, {
    buttons: [
      'copy', 'excel', 'pdf'
    ]
  });
  crudTable.buttons().container().appendTo( $(buttonsIdOrClass) );
}
```

I would be glad to create a pull request adding this feature, but I would need some help to complete the first step.

Thank you very much!

Mauro

**Comment by mberlanda** [comment]
A first working attempt I did on my project is the following:

**Created a new helper**
```rb
# app/helpers/datatable_helper.rb
# frozen_string_literal: true

module DatatableHelper
  def crud_datatable(model_name, *headers)
    DatatableHelper::Builder.table(model_name, *headers)
  end

  class Builder
    include ActionView::Helpers::TagHelper

    attr_accessor :headers, :model_name, :output_buffer
    attr_reader :table_class

    def initialize(model_name = :crud, *headers)
      @model_name = model_name || :crud
      @headers = headers || []
      @table_class = %w[table table-striped table-hover datatable-table]
    end

    def self.table(model_name = nil, *headers)
      model_name ||= :crud
      headers ||= []
      t = new(model_name, *headers)
      t.to_html
    end

    def to_html
      content_tag :div, class: 'container' do
        content_tag(:div, nil, class: "#{model_name}-index-buttons") +
          content_tag(:table, class: table_class, id: "#{model_name}-table") do
            content_tag(:thead) do
              headers.collect { |h| format_header(h) }.join.html_safe
            end
          end
      end
    end

    private

    def format_header(head)
      content_tag(:th, translate(head))
    end

    def translate(head)
      return head if model_name == :crud
      I18n.t(
        "activerecord.attributes.#{model_name}.#{head}",
        default: head
      )
    end
  end
end
```

And tested it:

```rb
#spec/helpers/datatable_helper_spec.rb
# frozen_string_literal: true

require 'rails_helper'

describe DatatableHelper do
  include DatatableHelper

  context 'default empty Builder' do
    before do
      @b = DatatableHelper::Builder.new
    end

    it '.model_name' do
      expect(@b.model_name).to eq(:crud)
    end

    it '.headers' do
      expect(@b.headers).to eq([])
    end

    it '.table_class' do
      expect(@b.table_class).to eq(
        %w[
          table table-striped table-hover datatable-table
        ]
      )
    end

    it '.to_html' do
      expect(@b.to_html).to eq(
        '<div class="container">'\
        '<div class="crud-index-buttons"></div>'\
        '<table class="table table-striped table-hover datatable-table"'\
        ' id="crud-table">'\
        '<thead></thead>'\
        '</table></div>'

      )
    end
  end

  context 'some values Builder' do
    it '#table' do
      actual = DatatableHelper::Builder.table(nil, 'a', 'b', 'c')
      expect(actual).to eq(
        '<div class="container">'\
        '<div class="crud-index-buttons"></div>'\
        '<table class="table table-striped table-hover datatable-table"'\
        ' id="crud-table">'\
        '<thead><th>a</th><th>b</th><th>c</th></thead>'\
        '</table></div>'
      )
    end
  end

  it 'crud_datatable' do
    actual = crud_datatable(nil, 'a', 'b', 'c')
    expect(actual).to eq(
      '<div class="container">'\
      '<div class="crud-index-buttons"></div>'\
      '<table class="table table-striped table-hover datatable-table"'\
      ' id="crud-table">'\
      '<thead><th>a</th><th>b</th><th>c</th></thead>'\
      '</table></div>'
    )
  end
end
```

Then I added, as per the previous post:

- `get :datatable_index` in routes.rb
- added the two methods in the controller
- added `shared/search.json.jbuilder`
- created under app/assets/javascripts `crud_datatable.js` where I defined `initializeCrudTable`
- required jquery, datatable.css, datatable.js, crud_datatable.js
- created a decorator with Draper

Added the following `index.html.haml`:

```haml
- @title ||= ti(:title, models: models_label)

- content_for(:actions, render('actions_index'))

= crud_datatable(model_class.name.underscore, *Crud::EventsController.search_columns)

:javascript
  $(function(){
    initializeCrudTable(
      '#{datatable_index_events_path}',
      '##{model_class.name.underscore}-table',
      '.#{model_class.name.underscore}-index-buttons'
    )
  })
```

And it works perfectly.

Would you be interested in a pull request with a custom generator for adding those libraries?

**Comment by codez** [comment]
Hi Mauro

Thank you for your detailed proposition. A major decision for dry_crud is to have no external dependencies (this is e.g. also why there is no built-in pagination), but to be extensible for all different kinds of use cases. Including datatables, even with a custom generator, would be against this decision. 

However, I think it should be no big deal to create a stand-alone gem (dry_crud_datatables?) that runs the dry_crud generator and then another one for datatables, resulting in the same artifacts. This solution would be modular, allowing users to choose from different configurations. 

Concerning your original problem with searching for dates and numbers: This is mostly a database issue when comparing apples to oranges. You first need to convert your dates and numbers to strings before searching in them. I am not aware of a generic solution for all databases, but it should be possible to adjust the code to do the necessary conversions for the database you use.
