### ISSUE TITLE
search bar doesn't show up in view

### ISSUE THREAD

**Issue by jtoy** [codez/dry_crud#18]
im on rails 5.0.6 and ruby 2.4.3
I added a categories controller:

class CategoriesController < CrudController
  self.search_columns = [:name, :description]
end

I can do everything with the controller, but a search bar never appears. there is no error, what can I do?

btw, love the project,been writing my own for years, but I'll use this going forward.

**Comment by jtoy** [comment]
did more debugging, app/views/list/index.html.erb  has search_support? it returns true. but the html for app/views/list/_search.html.erb
never renders. if I put trash into _search like <% wtf %> it will cause an exception though.....

**Comment by jtoy** [comment]
found the issue, but don't know why.
this doesn't work:
<% content_for(:tools, render('search')) if search_support? %>
this does:

<%=  render('search') if search_support? %>

**Comment by codez** [comment]
Did you modify your application.html.erb? The original renders the :tools section here: https://github.com/codez/dry_crud/blob/master/app/views/layouts/application.html.erb#L47

**Comment by jtoy** [comment]
I see, its because you expect this to work on a brand new application. I had my own layout already. So I guess I should merge them.  Maybe the docs should mention this?  Also really like your docs!

**Comment by codez** [comment]
The generator shows all file conflicts. If you review them, you see the differences and may adjust the code to your needs.
