### ISSUE TITLE
admin /namespace support?

### ISSUE THREAD

**Issue by jtoy** [codez/dry_crud#19]
I am trying to  use dry_crud with a model called Category under a  namescope of admin.  

Does dry_crud support this feature or do I need to modify all the views myself for this?
the views are all trying to use new_category_path instead of new_admin_category_path

**Comment by codez** [comment]
This is possible with a `self.nesting = :admin` line in your corresponding controllers. See the documentation here https://github.com/codez/dry_crud#nested-resources
